%!TEX root = ./jvk-blatt2.tex

\excercise{Exceptions - Mit dem Kopf durch die Wand}

Tank und Neo wollen nun in einer neuen Simulationsumgebung trainieren. 
Dabei soll Neo in einem potenziell gefährlichen Situation so schnell wie möglich zur nächsten Telefonstation laufen.

\begin{enumerate}
    \item Instanziiere die Simulation wie bekannt und mache dich mit dieser vertraut. 
        Benutze dabei den Task aus der Klasse \lstinline{Sheet2Task2} und den Verifier aus \lstinline{Sheet2Task2Verifier}.
    \item Als Operator hat Tank die Möglichkeit Hindernisse zwischen Neo und der Telefonstation einzufügen.
        Betrachte die Klasse \lstinline{Sheet2Task2} mit der Operation \lstinline{run} an der markierten Stelle.

        Überlege dir wie du an Tank's Stelle ein solches Hindernis an einer geeigneten Stelle platzieren kann.
        Eine geeignete Stelle ist eine beliebige Position ($x$, 0) für $1 \leq x \leq 9$.

        Was passiert, wenn man jetzt die Simulation wie zuvor ausführt?\\
        Zum genaueren Verständnis was nun passiert ließ den folgenden Abschnitt.
\end{enumerate}


\begin{Infobox}[Exception]
    Eine Exception ist ein Fehler der beim Ausführen des Programmes passieren kann wenn z.B. unvorhergesehene oder verbotene Sachen passieren.\\


    \textbf{Notiz}: Es gibt in PSE später genauere Unterscheidungen zwischen verschiedene Arten von Exceptions und Errors,... wir wollen das ganze hier mal vereinfachen, auch wenn es vielleicht dann nicht hundertprozentig genau ist.\\

    Als nächstes wollen wir den Aufbau einer Exception genauer verstehen.
    Überlege dazu was der folgende Programmausschnitt macht:

    \begin{lstlisting}[numbers=left,xleftmargin=2em,frame=single,framexleftmargin=1.5em]
public class Main{
    //Programmeinstieg
    public void main(){
        //some other code
        divide(1, 0);
    }
    
    public Integer divide(Integer a, Integer b){
        return a / b;
    }
}
    \end{lstlisting}

    Dabei lässt sich erkennen, dass an irgendeinem Punkt der Programmausführung durch 0 geteilt wird.\\
    Dieses ungewollte (''verbotene'') Verhalten wird bei der Programmausführung durch die folgende Exception ersichtlich:

    \begin{lstlisting}[keywords={}, breaklines=true, numbers=none]
java.lang.ArithmeticException: / by zero
    at de.unistuttgart.informatik.fius.jvk.Main.divide(Main.java:9)
    at de.unistuttgart.informatik.fius.jvk.Main.main(Main.java:5)
    \end{lstlisting}    

    Im Folgenden wollen wir kurz über ein paar für uns interessante Inhalte der Fehlermeldung reden:

    \begin{enumerate}[label=\roman*)]
        \item Art der Exception: Diese kann in der ersten Zeile abgelesen werden.\\
            In unserem Beispiel handelt es sich hier um eine \lstinline{ArithmeticException}.
        \item Nachricht der Exception: Diese befindet sich hinter der Exceptionart und soll dem Programmierer ggfs. mehr Informationen über den Fehler selbst geben.\\
            In unserem Fall ist die Nachricht \lstinline{"/ by zero"}.
        \item Fehlerstelle im Programm: Der Stacktrace (Weg von da wo die Exception passiert ist zu dem Aufrufer der Operation bis hin zur main Methode welcher der Programmeinstieg ist) der Exception beinhaltet weiterhin Informationen, wo im Programm die Exception geflogen also passiert ist.\\
            Hier interessiert uns fürs Erste nur die zweite Zeile. In unserem Beispiel deutet die zweite Zeile darauf hin, dass die Exception in der \lstinline{Main} Klasse in der \lstinline{divide}
        Operation in Zeile 9 geflogen ist.
    \end{enumerate}

\end{Infobox}


\begin{enumerate}[label=\alph*)] \setcounter{enumi}{2}
    \item Im Folgenden betrachten wir beispielhaft den Stacktrace einer Exception:
        \definecolor{ForestGreen}{rgb}{0.0, 0.5, 0.0}
        \begin{lstlisting}[keywords={}, breaklines=true, escapeinside={(*@}{@*)}]
de.unistuttgart.informatik.fius.icge.simulation.exception.IllegalMoveException: Solid Entity in the way
at de.unistuttgart.informatik.fius.icge.simulation.entity.MovableEntity.internalMove(MovableEntity.java:(*@{\color{ForestGreen}linenumber1}@*))
at de.unistuttgart.informatik.fius.icge.simulation.entity.MovableEntity.move(MovableEntity.java:(*@{\color{ForestGreen}linenumber2}@*))
at de.unistuttgart.informatik.fius.jvk.tasks.Sheet2Task2.run(Sheet2Task2.java:(*@{\color{ForestGreen}linenumber3}@*))
at de.unistuttgart.informatik.fius.icge.simulation.internal.tasks.StandardTaskRunner.executeTask(StandardTaskRunner.java:(*@{\color{ForestGreen}linenumber4}@*))
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:(*@{\color{ForestGreen}linenumber5}@*))
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:(*@{\color{ForestGreen}linenumber6}@*))
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:(*@{\color{ForestGreen}linenumber7}@*))
at java.base/java.lang.Thread.run(Thread.java:(*@{\color{ForestGreen}linenumber8}@*))
        \end{lstlisting}

        Dieser soll nun genauer analysiert werden:

        \begin{enumerate}
            \item[i)] Welche Exception wurde geworfen und was ist die Nachricht der Exception?
            \item[ii)] In welcher Operation wurde die Exception geworfen?
            \item[iii)] In dem obigen Stacktrace sind die dazugehörigen Zeilennummern verloren gegangen. Ersetze diese!

                Tipp: Schaue dazu in die Console.
        \end{enumerate}

    \item Wie wir gelernt haben sind Exceptions ein Anzeichen das etwas passiert ist was nicht passieren sollte, jetzt wollen wir die Exception verhindern.\\
        Dazu benutzen wir die Technik des Auskommentierens die ihr in Blatt 1 gelernt habt.\\
        Kommentiert in \lstinline{Sheet2Task2} so lange \lstinline{.move()} Kommandos aus, bis die Exception nicht mehr auftritt.

        Spielt die Reihenfolge in der ihr die Kommandos auskommentiert eine Rolle für das Ergebnis?
    \item Kommentiere erstmal wieder alle Zeilen ein.
        Kannst du Trotzdem verhindern, dass die Exception auftritt?
        Wenn ja wie ?

        Hinweis: In Aufgabe 1 hast du noch ein weiteres Kommando kennengelernt mit dem du Neo bewegen kannst.
        Du kannst Neo aber auch um die Wand herum gehen lassen.
    \item \optional Welche \q{linenumber} aus dem obigen Stacktrace ändert sich, wenn man zwischen den \lstinline{.move()} Aufrufen jeweils Leerzeilen einfügt?
    \item \optional Versuche möglichst viele unterschiedliche Möglichkeiten zu finden, um die Exception zu verhindern ohne eine der Zeilen vor dem Kommentar zu verändern.
        Werde Kreativ und versuche auch drastische Lösungen wie eine Wand zu löschen.\\
        Du kannst für diese Aufgabe auch Code von anderen Klassen vorübergehend ändern, solltest diese Änderungen aber hinterher wieder rückgängig machen.
        Wie viele unterschiedliche Möglichkeiten kannst du finden?
\end{enumerate}
 
